### ISSUE TITLE
rake hydrus:refreshfix fails

### ISSUE THREAD

**Issue by atz** [sul-dlss/hydrus#14]
I'm guessing this is making assumptions about the network availability of a workflow server.  I'm on VPN but still get error:

```
$ rake hydrus:refreshfix --trace
** Invoke hydrus:refreshfix (first_time)
** Execute hydrus:refreshfix
** Invoke hydrus:loadfix (first_time)
** Invoke db:fixtures:load (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:fixtures:load
** Execute hydrus:loadfix
DEPRECATION WARNING: has_relationship is deprecated and will be removed from . (called from <class:Collection> at /Users/atz/repos/hydrus/app/models/hydrus/collection.rb:51)
** Invoke hydrus:reindex_workflow_objects (first_time)
** Invoke environment 
** Execute hydrus:reindex_workflow_objects
** Invoke hydrus:reindex (first_time)
** Invoke environment 
** Execute hydrus:reindex
Reindexing druid:oo000oo0099 in solr
** Invoke hydrus:reindex (first_time)
** Invoke environment 
** Execute hydrus:reindex
Reindexing druid:oo000oo0098 in solr
** Invoke hydrus:refresh_workflows (first_time)
** Execute hydrus:refresh_workflows
rake aborted!
RestClient::InternalServerError: 500 Internal Server Error
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/abstract_response.rb:48:in `return!'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:269:in `process_result'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:212:in `block in transmit'
/Users/atz/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rest-client-1.6.8/lib/restclient/resource.rb:76:in `put'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/dor-workflow-service-1.7.2/lib/dor/services/workflow_service.rb:34:in `create_workflow'
/Users/atz/repos/hydrus/lib/tasks/fixtures.rake:189:in `block (3 levels) in <top (required)>'
/Users/atz/repos/hydrus/lib/tasks/fixtures.rake:182:in `each'
/Users/atz/repos/hydrus/lib/tasks/fixtures.rake:182:in `block (2 levels) in <top (required)>'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:240:in `call'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:240:in `block in execute'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:235:in `each'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:235:in `execute'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/atz/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:165:in `invoke'
/Users/atz/repos/hydrus/lib/tasks/fixtures.rake:130:in `block (3 levels) in <top (required)>'
/Users/atz/repos/hydrus/lib/tasks/fixtures.rake:128:in `each'
/Users/atz/repos/hydrus/lib/tasks/fixtures.rake:128:in `block (2 levels) in <top (required)>'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:240:in `call'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:240:in `block in execute'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:235:in `each'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:235:in `execute'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/atz/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/task.rb:165:in `invoke'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:156:in `invoke_task'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:112:in `block (2 levels) in top_level'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:112:in `each'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:112:in `block in top_level'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:121:in `run_with_threads'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:106:in `top_level'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:84:in `block in run'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:182:in `standard_exception_handling'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/lib/rake/application.rb:79:in `run'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/gems/rake-10.4.0/bin/rake:33:in `<top (required)>'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/bin/rake:23:in `load'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/bin/rake:23:in `<main>'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
/Users/atz/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => hydrus:refresh_workflows
```

**Comment by peetucket** [comment]
this works now
