### ISSUE TITLE
[hydrus/production] RestClient::InternalServerError: 500 Internal Server Error

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/hydrus#248]
## Backtrace

    line 120 of [PROJECT_ROOT]/app/models/hydrus/generic_object_stuff.rb: publish_metadata
    line 76 of [PROJECT_ROOT]/app/models/hydrus/collection.rb: save
    line 81 of [PROJECT_ROOT]/app/controllers/hydrus_collections_controller.rb: update

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49897/faults/44121155)

**Comment by jcoyne** [comment]
```
publishable.rb 113 publish_metadata_remotely(...)
[GEM_ROOT]/gems/dor-services-5.32.1/lib/dor/models/concerns/publishable.rb:113:in `publish_metadata_remotely'

111       dor_services = Dor::Config.dor_services.rest_client
112       endpoint = dor_services["v1/objects/#{pid}/publish"]
113       endpoint.post ''
114       endpoint.url
115     end

generic_object_stuff.rb 120 publish_metadata(...)
[PROJECT_ROOT]/app/models/hydrus/generic_object_stuff.rb:120:in `publish_metadata'

118     return unless should_start_assembly_wf
119     cannot_do(:publish_metadata) unless is_assemblable()
120     publish_metadata_remotely
121   end


```

**Comment by jcoyne** [comment]
Likely caused by https://github.com/sul-dlss/dor-services-app/issues/188

**Comment by jcoyne** [comment]
Closed in dor-services-app
