### ISSUE TITLE
Loading fixtures tries to connect to workflow service

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/hydrus#39]
```
rake aborted!

RestClient::RequestTimeout: Request Timeout

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:427:in `rescue in transmit'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-workflow-service-1.7.7/lib/dor/services/workflow_service.rb:523:in `block in workflow_resource_method'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/retries-0.0.5/lib/retries.rb:46:in `call'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/retries-0.0.5/lib/retries.rb:46:in `with_retries'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-workflow-service-1.7.7/lib/dor/services/workflow_service.rb:520:in `workflow_resource_method'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-workflow-service-1.7.7/lib/dor/services/workflow_service.rb:110:in `get_workflow_xml'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/datastreams/workflow_ds.rb:45:in `content'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/datastreams/workflow_ds.rb:41:in `ng_xml'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/om-1.8.1/lib/om/xml/document.rb:104:in `find_by_xpath'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/om-1.8.1/lib/om/xml/dynamic_node.rb:85:in `nodeset'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/datastreams/workflow_ds.rb:57:in `workflows'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/datastreams/workflow_ds.rb:84:in `to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/base.rb:314:in `block in to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/base.rb:313:in `each_value'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/base.rb:313:in `to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/models/identifiable.rb:60:in `to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/models/editable.rb:11:in `to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/models/describable.rb:189:in `to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/dor-services-4.24.0/lib/dor/models/processable.rb:153:in `to_solr'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/persistence.rb:89:in `update_index'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/fixture_loader.rb:38:in `index'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/fixture_loader.rb:33:in `import_and_index'

/home/travis/build/sul-dlss/hydrus/vendor/bundle/ruby/2.1.0/gems/active-fedora-5.7.1/lib/active_fedora/fixture_loader.rb:28:in `reload'

/home/travis/build/sul-dlss/hydrus/lib/tasks/fixtures.rake:27:in `block (3 levels) in <top (required)>'

/home/travis/build/sul-dlss/hydrus/lib/tasks/fixtures.rake:26:in `each'

/home/travis/build/sul-dlss/hydrus/lib/tasks/fixtures.rake:26:in `block (2 levels) in <top (required)>'

/home/travis/build/sul-dlss/hydrus/lib/tasks/fixtures.rake:130:in `block (3 levels) in <top (required)>'

/home/travis/build/sul-dlss/hydrus/lib/tasks/fixtures.rake:128:in `each'

/home/travis/build/sul-dlss/hydrus/lib/tasks/fixtures.rake:128:in `block (2 levels) in <top (required)>'

/home/travis/build/sul-dlss/hydrus/lib/tasks/ci.rake:19:in `block (2 levels) in <top (required)>'
```

**Comment by jcoyne** [comment]
@atz is this the same concern as in #23?
