### ISSUE TITLE
Can't run console on stage

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/hydrus#79]
```
$ RAILS_ENV=dortest bundle exec rails c
/var/home/lyberadmin/hydrus/releases/20170719174230/config/application.rb:78: warning: key "question" is duplicated and overwritten on line 78
DEPRECATION WARNING: has_relationship is deprecated and will be removed from a future release. (called from <class:Collection> at /var/home/lyberadmin/hydrus/releases/20170719174230/app/models/hydrus/collection.rb:51)
/var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/test_case.rb:2:in `<top (required)>'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /var/home/lyberadmin/hydrus/shared/bundle/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
```

**Comment by jcoyne** [comment]
Fixed by #80
